### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by flpfar** [bettercallazamat/bot-using-ruby#3]
Awesome project, Azamat!

- Send a message explaining how to use after you give your github username
- Your main is taking care of everything about telegram. Maybe it should be better to have a different class for it and just use it inside of main when necessary. In main, could be only something like Telegram.start_bot()
- Try to think about how to desestructurate your classes a little. Your classes are taking to many responsibilities and it can be hard to maintain.

Keep the great job!!

**Comment by bettercallazamat** [comment]
Thank you for your feedback. I have applied them.
