### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by flpfar** [bettercallazamat/bot-using-ruby#5]
Great job, Azamat!! You've gone far from the requirements, that's really cool!

Some improvements you might implement:
 - Requires in main maybe are unnecessary 
 - Maybe in bot, in case when text_reply repeat could be avoided

Keep the great job, man!

**Comment by bettercallazamat** [comment]
Thanks for the feedback, improvements implemented, except related to text_reply, could not find a way to decrease its usage.
